---
framework: mocha
postMerge:
  pattern:
    - "test/*.test.js"
preMerge:
  pattern:
    - "test/*.test.js"
preRun:
  - npm ci
  - echo 'export NODE_OPTIONS="-r esm"' > ~/.bashrc
  - source ~/.bashrc
postRun:
  - node --version
version: 2.0
