---
framework: mocha
postMerge:
  pattern:
    - "test/*.test.js"
preMerge:
  pattern:
    - "test/*.test.js"
preRun:
  - npm ci
  - export NODE_OPTIONS='-r esm'
postRun:
  - node --version
version: 2.0
